effect @s speed 15
effect @s haste 15
effect @s strength 15
effect @s instant_health 15
effect @s jump_boost 15
effect @s regeneration 15
effect @s resistance 15
effect @s fire_resistance 15
effect @s water_breathing 15
effect @s invisibility 15
effect @s night_vision 15
effect @s health_boost 15
effect @s absorption 15
effect @s saturation 15
effect @s slow_falling 15
effect @s conduit_power 15
effect @s village_hero 15
effect @s slowness 15
effect @s mining_fatigue 15
effect @s instant_damage 15
effect @s nausea 15
effect @s blindness 15
effect @s hunger 15
effect @s weakness 15
effect @s poison 15
effect @s wither 15
effect @s fatal_poison 15
effect @s bad_omen 15
effect @s darkness 15
effect @s levitation 15