effect @s speed 0
effect @s haste 0
effect @s strength 0
effect @s instant_health 0
effect @s jump_boost 0
effect @s regeneration 0
effect @s resistance 0
effect @s fire_resistance 0
effect @s water_breathing 0
effect @s invisibility 0
effect @s night_vision 0
effect @s health_boost 0
effect @s absorption 0
effect @s saturation 0
effect @s slow_falling 0
effect @s conduit_power 0
effect @s village_hero 0