effect @s speed 60
effect @s haste 60
effect @s strength 60
effect @s instant_health 60
effect @s jump_boost 60
effect @s regeneration 60
effect @s resistance 60
effect @s fire_resistance 60
effect @s water_breathing 60
effect @s invisibility 60
effect @s night_vision 60
effect @s health_boost 60
effect @s absorption 60
effect @s saturation 60
effect @s slow_falling 60
effect @s conduit_power 60
effect @s village_hero 60
effect @s slowness 60
effect @s mining_fatigue 60
effect @s instant_damage 60
effect @s nausea 60
effect @s blindness 60
effect @s hunger 60
effect @s weakness 60
effect @s poison 60
effect @s wither 60
effect @s fatal_poison 60
effect @s bad_omen 60
effect @s darkness 60
effect @s levitation 60