effect @s slowness 60
effect @s mining_fatigue 60
effect @s instant_damage 60
effect @s nausea 60
effect @s blindness 60
effect @s hunger 60
effect @s weakness 60
effect @s poison 60
effect @s wither 60
effect @s fatal_poison 60
effect @s bad_omen 60
effect @s darkness 60
effect @s levitation 60