effect @s slowness 15
effect @s mining_fatigue 15
effect @s instant_damage 15
effect @s nausea 15
effect @s blindness 15
effect @s hunger 15
effect @s weakness 15
effect @s poison 15
effect @s wither 15
effect @s fatal_poison 15
effect @s bad_omen 15
effect @s darkness 15
effect @s levitation 15