effect @s speed 60
effect @s haste 60
effect @s strength 60
effect @s instant_health 60
effect @s jump_boost 60
effect @s regeneration 60
effect @s resistance 60
effect @s fire_resistance 60
effect @s water_breathing 60
effect @s invisibility 60
effect @s night_vision 60
effect @s health_boost 60
effect @s absorption 60
effect @s saturation 60
effect @s slow_falling 60
effect @s conduit_power 60
effect @s village_hero 60