effect @s speed 30
effect @s haste 30
effect @s strength 30
effect @s instant_health 30
effect @s jump_boost 30
effect @s regeneration 30
effect @s resistance 30
effect @s fire_resistance 30
effect @s water_breathing 30
effect @s invisibility 30
effect @s night_vision 30
effect @s health_boost 30
effect @s absorption 30
effect @s saturation 30
effect @s slow_falling 30
effect @s conduit_power 30
effect @s village_hero 30
effect @s slowness 30
effect @s mining_fatigue 30
effect @s instant_damage 30
effect @s nausea 30
effect @s blindness 30
effect @s hunger 30
effect @s weakness 30
effect @s poison 30
effect @s wither 30
effect @s fatal_poison 30
effect @s bad_omen 30
effect @s darkness 30
effect @s levitation 30