tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.title" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.introduction" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.empty" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.usage.title" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.usage.1" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.usage.2" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.empty" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.gets.title" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.gets.1" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.gets.2" } ] }
tellraw @s { "rawtext" : [ { "translate" : "hy.tutorial.fuel_metals.gets.3" } ] }