effect @s slowness 0
effect @s mining_fatigue 0
effect @s instant_damage 0
effect @s nausea 0
effect @s blindness 0
effect @s hunger 0
effect @s weakness 0
effect @s poison 0
effect @s wither 0
effect @s fatal_poison 0
effect @s bad_omen 0
effect @s darkness 0
effect @s levitation 0