effect @s minecraft:speed 0
effect @s minecraft:haste 0
effect @s minecraft:strength 0
effect @s minecraft:instant_health 0
effect @s minecraft:jump_boost 0
effect @s minecraft:regeneration 0
effect @s minecraft:resistance 0
effect @s minecraft:fire_resistance 0
effect @s minecraft:water_breathing 0
effect @s minecraft:invisibility 0
effect @s minecraft:night_vision 0
effect @s minecraft:health_boost 0
effect @s minecraft:absorption 0
effect @s minecraft:saturation 0
effect @s minecraft:slow_falling 0
effect @s minecraft:conduit_power 0
effect @s minecraft:village_hero 0