effect @s slowness 30
effect @s mining_fatigue 30
effect @s instant_damage 30
effect @s nausea 30
effect @s blindness 30
effect @s hunger 30
effect @s weakness 30
effect @s poison 30
effect @s wither 30
effect @s fatal_poison 30
effect @s bad_omen 30
effect @s darkness 30
effect @s levitation 30